apiVersion: v1
kind: Service
metadata:
  name: {{ include "matter-server.fullname" . }}
  labels:
    {{- include "matter-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.matterServer.port }}
      targetPort: websocket
      protocol: TCP
      name: websocket
  selector:
    {{- include "matter-server.selectorLabels" . | nindent 4 }}
